repos:
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        args: [ "--config", "pyproject.toml" ]  # keeping as an example for overwritting the cmd args
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
